CREATE SCHEMA IF NOT EXISTS delivery;

CREATE TABLE IF NOT EXISTS delivery.address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(50),
    city VARCHAR(50),
    street VARCHAR(100),
    house VARCHAR(5),
    flat VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS delivery.deliveries (
    delivery_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_address_id BIGINT,
    to_address_id BIGINT,
    delivery_state VARCHAR(50),
    FOREIGN KEY (from_address_id) REFERENCES delivery.address (address_id),
    FOREIGN KEY (to_address_id) REFERENCES delivery.address (address_id)
);
