server:
  port: 8084
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create-drop
    datasource:
      url: jdbc:postgresql://localhost:5432/warehouse
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    instance-id: warehouse:${random.value}